name: CI tests
on:
  - push
  - pull_request
env:
  REPO_DIR: ansible_collections/maas/maas
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_DIR }}
      - name: Build docs
        run: |
          pip install tox
          env -C "$GITHUB_WORKSPACE/$REPO_DIR" -- tox -e docs

  sanity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_DIR }}
      - name: Sanity check
        run: |
          pip install tox
          env -C "$GITHUB_WORKSPACE/$REPO_DIR" -- tox -e sanity

  units-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_DIR }}
      - name: Run unit tests
        run: |
          pip install tox
          env -C "$GITHUB_WORKSPACE/$REPO_DIR" -- tox -e coverage
